spring.application.name=TrackerBackend

spring.data.mongodb.uri=mongodb://alisha:Fazilars123@expense-tracker-db.cd6iswegk7zq.ap-south-1.docdb.amazonaws.com:27017/TrackerProject?tls=true&retryWrites=false

server.port=8090
